import { Brand, make } from 'ts-brand'

export type CustomerID = Brand<number, 'CustomerID'>
export const CustomerID = make<CustomerID>()
export type CustomerType = Brand<boolean, 'CustomerType'>
export const CustomerType = make<CustomerType>()
export type CustomerExternalNumber = Brand<string, 'CustomerExternalNumber'>
export const CustomerExternalNumber = make<CustomerExternalNumber>()
export type CustomerGDPRAccept = Brand<boolean, 'CustomerGDPRAccept'>
export const CustomerGDPRAccept = make<CustomerGDPRAccept>()
export type CustomerISWarrantyCustomer = Brand<boolean, 'CustomerISWarrantyCustomer'>
export const CustomerISWarrantyCustomer = make<CustomerISWarrantyCustomer>()
export type CustomerAcceptsMarketing = Brand<boolean, 'CustomerAcceptsMarketing'>
export const CustomerAcceptsMarketing = make<CustomerAcceptsMarketing>()
export type CustomerComapanyName = Brand<string, 'CustomerComapanyName'>
export const CustomerComapanyName = make<CustomerComapanyName>()
export type CustomerOrgNumber = Brand<string, 'CustomerOrgNumber'>
export const CustomerOrgNumber = make<CustomerOrgNumber>()
export type CustomerFirstName = Brand<string, 'CustomerFirstName'>
export const CustomerFirstName = make<CustomerFirstName>()
export type CustomerLastName = Brand<string, 'CustomerLastName'>
export const CustomerLastName = make<CustomerLastName>()
export type CustomerReference = Brand<string, 'CustomerReference'>
export const CustomerReference = make<CustomerReference>()
export type CustomerEmail = Brand<string, 'CustomerEmail'>
export const CustomerEmail = make<CustomerEmail>()
export type CustomerPhoneNumber = Brand<string, 'CustomerPhoneNumber'>
export const CustomerPhoneNumber = make<CustomerPhoneNumber>()
export type CustomerAddress = Brand<string, 'CustomerAddress'>
export const CustomerAddress = make<CustomerAddress>()
export type CustomerZipCode = Brand<string, 'CustomerZipCode'>
export const CustomerZipCode = make<CustomerZipCode>()
export type CustomerAddressCity = Brand<string, 'CustomerAddressCity'>
export const CustomerAddressCity = make<CustomerAddressCity>()
export type CustomerCountry = Brand<string, 'CustomerCountry'>
export const CustomerCountry = make<CustomerCountry>()
export type CustomerHasCard = Brand<boolean, 'CustomerHasCard'>
export const CustomerHasCard = make<CustomerHasCard>()
export type CustomerCardNumber = Brand<string, 'CustomerCardNumber'>
export const CustomerCardNumber = make<CustomerCardNumber>()
export type CustomerCarValid = Brand<boolean, 'CustomerCarValid'>
export const CustomerCarValid = make<CustomerCarValid>()
export type CustomerKeyNumber = Brand<string, 'CustomerKeyNumber'>
export const CustomerKeyNumber = make<CustomerKeyNumber>()
export type CustomerNotesShared = Brand<string, 'CustomerNotesShared'>
export const CustomerNotesShared = make<CustomerNotesShared>()
export type CustomerNotes = Brand<string, 'CustomerNotes'>
export const CustomerNotes = make<CustomerNotes>()
